

services:
  app:
    build: .
    container_name: phil_rag_app
    volumes:
      - .:/app
    depends_on:
      - postgres
      - neo4j
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/phil_rag
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jpassword

  postgres:
    image: postgres:15
    container_name: phil_rag_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phil_rag
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: phil_rag_neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  pg_data:
  neo4j_data:
