from pinecone_operations import *

query_text = "The preferred context of a system is defined by the set of basis vectors generated by the biorthogonal decomposition of the state. Quantum mechanics: modal interpretations of. This is the actualization rule of BDMI."
semantic_search(query_text)

